name: buld-deploy

on:
  push:
    branches:
      - main
  workflow_dispatch
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create env file
        env:
          ENV_FILE_TEXT: ${{ secrets.ENV_FILE_TEXT }}
        run: |
          echo $ENV_FILE_TEXT > .env.local

      - name: Set node
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Setup dependencies
        run: npm ci

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: S3 Sync
        env:
          S3_SYNC_BUCKET: ${{ secrets.S3_SYNC_BUCKET }}
        run: |
          aws s3 sync s3://$S3_SYNC_BUCKET/text content/text --delete
          aws s3 sync s3://$S3_SYNC_BUCKET/public public --delete

      - name: Build
        run: npm run build

      - name: Export
        run: npm run export

      - name: S3 HOST
        env:
          S3_HOST_BUCKET: ${{ secrets.S3_HOST_BUCKET }}
        run: |
          aws s3 sync out/ s3://$S3_HOST_BUCKET
